os:
  - linux
  - osx
dist: trusty
sudo: false

language: node_js
node_js:
  - lts/* #latest LTS release
  - node  #latest stable release

install:
  - npm i
before_script:
  - npm run lint
  - npm run check
script:
  - npm run cover
after_script:
  - cat ./build/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email: false

branches:
  only:
    - master