sudo: false

# trust dist provides a modern build chain (as opposed to 'precise' dist)
# which absolves us from having to install compilers and stuff
dist: trusty

language: node_js

matrix:
  fast_finish: true
  include:
    - node_js: 4
    - node_js: lts/*
    - node_js: node
      after_success: # Generate coverage report and send report to coveralls.io
        - npm run cover
        - cat ./build/lcov.info | ./node_modules/coveralls/bin/coveralls.js

install:
  - npm i

script:
  - npm t

notifications:
  email: false