sudo: false
dist: trusty

language: node_js
os:
  - linux
  - osx
node_js:
  - 8
  - node

matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: 8
      env: COVERAGE=true
  allow_failures:
    - os: osx
    - node_js: node

before_script:
  - if [[ "$COVERAGE" == true ]] then; npm run lint fi;
  - if [[ "$COVERAGE" == true ]] then; npm run check fi;

after_script:
  - if [[ "$COVERAGE" == true ]] then; npm run cover fi;
  - if [[ "$COVERAGE" == true ]] then; cat ./build/lcov.info | ./node_modules/coveralls/bin/coveralls.js fi;

notifications:
  email: false

branches:
  only:
    - master