sudo: false

# trust dist provides a modern build chain (as opposed to 'precise' dist)
# which absolves us from having to install compilers and stuff
dist: trusty

language: node_js

node_js:
  - "4"
  - "lts/*"
  - "node"

install:
  - npm i

script:
  - npm t

# Generate coverage report and send report to coveralls.io
after_success:
  - npm run cover
  - cat ./build/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email: false

branches:
  only:
    - master