environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i

test_script:
  - npm run lint
  - npm t
  - npm run check

build: off

branches:
  only:
    - master